import type { Hackathon, Judge, Project } from "./types"

export const mockHackathons: Hackathon[] = [
  {
    id: "1",
    name: "ChainSpark Hackathon",
    description:
      "ChainSpark Hackathon was born from a simple but radical belief: true innovation shouldn't be strangled by black-box algorithms or centralized gatekeepers.",
    startDate: "2025-06-17T19:00:00",
    endDate: "2025-07-19T19:00:00",
    rules: "Open to all developers. Team size: 1-5 members. Original projects only.",
    prizes: [
      { id: "p1", title: "Tech Fairness Exploration Awards", amount: 18000, currency: "USD", winners: 9 },
      { id: "p2", title: "FAIR3 Public Infrastructure Awards", amount: 6000, currency: "USD", winners: 3 },
    ],
    banner:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/01-3-One-hackathon-Full-view-etrFV597ZXqQz5LhuZbnDsEV4KjTA9.png",
    teamSizeLimit: 5,
    status: "ongoing",
    totalParticipants: 234,
    totalProjects: 45,
    assignedJudges: ["j1", "j2", "j3"],
  },
  {
    id: "2",
    name: "Web3 Innovate Jam",
    description: "Build innovative applications that integrate the MetaMask Card, LUFI, and other Web3 technologies.",
    startDate: "2025-05-10T00:00:00",
    endDate: "2025-05-12T23:59:00",
    rules: "All tech stacks welcome. Focus on Web3 integration.",
    prizes: [{ id: "p3", title: "Grand Prize", amount: 30000, currency: "USD", winners: 1 }],
    teamSizeLimit: 4,
    status: "upcoming",
    totalParticipants: 0,
    totalProjects: 0,
    assignedJudges: ["j1", "j2"],
  },
  {
    id: "3",
    name: "DeFi Builder Sprint",
    description: "A high-octane sprint to redefine the future of AI, Data, and Web3.",
    startDate: "2025-04-15T00:00:00",
    endDate: "2025-04-20T23:59:00",
    rules: "DeFi focused projects only.",
    prizes: [{ id: "p4", title: "Winner Prize", amount: 25000, currency: "USD", winners: 3 }],
    teamSizeLimit: 5,
    status: "completed",
    totalParticipants: 189,
    totalProjects: 38,
    assignedJudges: ["j2", "j3"],
  },
]

export const mockJudges: Judge[] = [
  {
    id: "j1",
    name: "Sarah Chen",
    email: "sarah.chen@example.com",
    expertise: "Blockchain & Smart Contracts",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    assignedHackathons: ["1", "2"],
  },
  {
    id: "j2",
    name: "Michael Rodriguez",
    email: "michael.r@example.com",
    expertise: "DeFi & Web3",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=michael",
    assignedHackathons: ["1", "2", "3"],
  },
  {
    id: "j3",
    name: "Emily Watson",
    email: "emily.w@example.com",
    expertise: "UI/UX & Product Design",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emily",
    assignedHackathons: ["1", "3"],
  },
]

export const mockProjects: Project[] = [
  {
    id: "pr1",
    hackathonId: "1",
    teamName: "Init Club Pro",
    description:
      "Init Club Pro was born from a simple but radical belief: true innovation shouldn't be strangled by black-box algorithms or centralized gatekeepers.",
    githubLink: "https://github.com/example/init-club",
    demoLink: "https://demo.initclub.com",
    submittedAt: "2025-06-20T10:00:00",
    teamSize: 4,
    technologies: ["React", "Solidity", "Web3.js", "IPFS"],
    scores: [
      {
        judgeId: "j1",
        judgeName: "Sarah Chen",
        innovation: 9,
        design: 8,
        functionality: 9,
        presentation: 8,
        comments: "Excellent implementation of blockchain concepts.",
        totalScore: 34,
      },
    ],
    averageScore: 8.5,
  },
  {
    id: "pr2",
    hackathonId: "1",
    teamName: "Ward",
    description:
      "Ward was born from a simple but radical belief: true innovation shouldn't be strangled by black-box algorithms.",
    githubLink: "https://github.com/example/ward",
    demoLink: "https://demo.ward.com",
    submittedAt: "2025-06-21T14:30:00",
    teamSize: 3,
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Ethereum"],
    scores: [
      {
        judgeId: "j1",
        judgeName: "Sarah Chen",
        innovation: 8,
        design: 9,
        functionality: 8,
        presentation: 9,
        comments: "Great UI/UX design and user experience.",
        totalScore: 34,
      },
      {
        judgeId: "j2",
        judgeName: "Michael Rodriguez",
        innovation: 9,
        design: 8,
        functionality: 9,
        presentation: 8,
        comments: "Solid technical implementation.",
        totalScore: 34,
      },
    ],
    averageScore: 8.5,
  },
  {
    id: "pr3",
    hackathonId: "1",
    teamName: "Wiral",
    description:
      "Wiral was born from a simple but radical belief: true innovation shouldn't be strangled by black-box algorithms.",
    githubLink: "https://github.com/example/wiral",
    submittedAt: "2025-06-22T09:15:00",
    teamSize: 5,
    technologies: ["Vue.js", "Node.js", "MongoDB", "Web3"],
    scores: [],
    averageScore: 0,
  },
  {
    id: "pr4",
    hackathonId: "1",
    teamName: "DeFi Protocol",
    description: "A decentralized finance protocol for transparent and fair financial transactions.",
    githubLink: "https://github.com/example/defi-protocol",
    demoLink: "https://demo.defi-protocol.com",
    submittedAt: "2025-06-23T16:45:00",
    teamSize: 4,
    technologies: ["Solidity", "Hardhat", "React", "Ethers.js", "DeFi"],
    scores: [],
    averageScore: 0,
  },
  {
    id: "pr5",
    hackathonId: "1",
    teamName: "ChainGuard",
    description: "Security-focused blockchain monitoring and auditing tool for smart contracts.",
    githubLink: "https://github.com/example/chainguard",
    submittedAt: "2025-06-24T11:20:00",
    teamSize: 3,
    technologies: ["Python", "Solidity", "React", "Security"],
    scores: [
      {
        judgeId: "j3",
        judgeName: "Emily Watson",
        innovation: 7,
        design: 8,
        functionality: 8,
        presentation: 7,
        comments: "Good security approach, needs better documentation.",
        totalScore: 30,
      },
    ],
    averageScore: 7.5,
  },
  {
    id: "pr6",
    hackathonId: "3",
    teamName: "TokenSwap",
    description: "Decentralized token exchange platform with advanced trading features.",
    githubLink: "https://github.com/example/tokenswap",
    demoLink: "https://demo.tokenswap.com",
    submittedAt: "2025-04-18T13:00:00",
    teamSize: 5,
    technologies: ["React", "Solidity", "Web3.js", "DeFi", "Trading"],
    scores: [
      {
        judgeId: "j2",
        judgeName: "Michael Rodriguez",
        innovation: 9,
        design: 9,
        functionality: 10,
        presentation: 9,
        comments: "Outstanding project with excellent execution.",
        totalScore: 37,
      },
    ],
    averageScore: 9.25,
  },
]
